### ISSUE TITLE
Creating an abomination.

### ISSUE THREAD

**Issue by mudrhiod** [raymond-1227/sunroof-blaster#1]
I will report this repo until it gets banned.

**Comment by raymond-1227** [comment]
no

**Comment by mudrhiod** [comment]
Delete this when? (Now)

**Comment by raymond-1227** [comment]
You mean this issue? Yeah sure it should've never existed.

**Comment by mudrhiod** [comment]
NO DELETE THE REPO

**Comment by raymond-1227** [comment]
Sorry but I refuse your outrageous idea.

**Comment by mudrhiod** [comment]
This repo is an outrageous idea

**Comment by raymond-1227** [comment]
The idea of this project is about an ultimate listening experience dedicated to listening to the song "Sunroof" by Nicky Youre & Dazy, which includes the use of a dynamic lyrics display and high quality audio of the song. So again, no, this is not an outrageous idea, this idea was made under careful decisions and created exquisitely.

**Comment by mudrhiod** [comment]
The problem is the song choice, thnx

**Comment by raymond-1227** [comment]
Why does the song bother you? Is the song not good?
